### ISSUE TITLE
Use tslint.loadConfigurationFromPath() to load tslint.json

### ISSUE THREAD

**Issue by unional** [panuhorsmalahti/gulp-tslint#60]
https://github.com/panuhorsmalahti/gulp-tslint/blob/master/index.ts#L130
`tslint.loadConfigurationFromPath()`
https://github.com/palantir/tslint/blob/master/src/tslint.ts#L32
will resolve `rulesDirectory` as well as handling `extends` (coming soon).
I think this is the cause for #55 

cc/ @JKillian

**Comment by unional** [comment]
Specifically for #55,  https://github.com/panuhorsmalahti/gulp-tslint/blob/master/index.ts#L153
```js
rulesDirectory: pluginOptions.rulesDirectory || null
```
should be
```js
rulesDirectory: pluginOptions.rulesDirectory || fileOptions.rulesDirectory || null
```

But the file loading should still come from `loadConfigurationFromFile()`

My problem is the `extends` does not get resolved. The rules are not merged.

**Comment by panuhorsmalahti** [comment]
Yeah, replacing rcloader would be nice. However, we need to check there's no regression related to configuration merging (e.g. related to https://github.com/panuhorsmalahti/gulp-tslint/issues/49 ).

Any link to the upcoming extends feature?

**Comment by panuhorsmalahti** [comment]
We can't use ``tslint.loadConfigurationFromPath()`` directly, as the function reads the file from the supplied path directly instead of looking for it: https://github.com/palantir/tslint/blob/f4b3064a167226b52ee8027797a2c3942f5e6e7a/src/configuration.ts#L131

A "hack" workaround would be to implement a new callback parameter to rcloader which returns the location of tslint.json, which we can then load using ``tslint.loadConfigurationFromPath()``. However, there should be better alternatives.

tsloader's fix can also be utilized (with the rcloader change) and is straightforward enough: https://github.com/wbuchwalter/tslint-loader/commit/2cd55a00aa8990b9955142956e36038c4d2191b6

However, the ideal fix would probably utilize ``findConfigurationPath`` in https://github.com/palantir/tslint/blob/f4b3064a167226b52ee8027797a2c3942f5e6e7a/src/configuration.ts#L87

**Comment by JKillian** [comment]
Can you use [`findConfiguration`](https://github.com/palantir/tslint/blob/f4b3064a167226b52ee8027797a2c3942f5e6e7a/src/configuration.ts#L72)? This is how I'll imagine that most 3rd-party tools will want to load configurations.

**Comment by unional** [comment]
Extends feature: https://github.com/palantir/tslint/pull/1016

I'm work on it today or tomorrow if I get some time. It is now unblocked.

**Comment by patsissons** [comment]
for a quick stop-gap until `gulp-tslint` is using `findConfiguration` internally, you can inject the config when piping.

```
import tslint from 'gulp-tslint'

gulp.task('lint:ts', () => {
  gulp
    .src('*.ts')
    .pipe(tslint({ configuration: require('tslint').findConfiguration() }))
    .pipe(tslint.report('verbose', { emitError: true, summarizeFailureOutput: true }));
});
```

```
// tslint.json
{
  "extends": "tslint/docs/sample.tslint",
  "rules": {
  }
}
```

**Comment by unional** [comment]
The extends feature is released in `3.7.0`

**Comment by valorkin** [comment]
+1
this is extremely valuable feature
https://npmjs.org/tslint-config-valorsoft
```json
// tslint.json
{
  "extends": "./node_modules/tslint-config-valorsoft/tslint.json",
  "rulesDirectory": "./node_modules/codelyzer/dist/src"
}
```
this works fine with tslint (in WebStorm)
but gulp-tslint fails to load it

**Comment by JKillian** [comment]
These are the changes I made to grunt-tslint so new features like `extends` work correctly: https://github.com/palantir/grunt-tslint/pull/47/files

I don't know the gulp model very well / how it interacts with the filesystem, but perhaps something similar would be possible here?
